routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\Client\BlogViewController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\CheckOutController;
use App\Http\Controllers\Client\ClientProductController;
use App\Http\Controllers\Client\ContactController;
use App\Http\Controllers\Client\EmailController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\LoginController;
use App\Http\Controllers\Client\OrderController as ClientOrders;
use App\Http\Controllers\ContactController as ControllersContactController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\LoginUserController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VideoProductController;
use App\Http\Livewire\HeaderSearchComponent;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/client/cart', [HomeController::class, 'cart'])->name('client.cart');
Route::get('client/contact', [ContactController::class,'index'])->name('client.contact');
Route::post('client/contact', [ContactController::class,'store'])->name('client.contact');
Route::get('client/blog', [BlogViewController::class,'index'])->name('client.blog');
Route::get('client/blog/details/{id}', [BlogViewController::class, 'blog_details'])->name('client.blog.details');

Route::post('client/blog/sreach', [BlogViewController::class,'sreach'])->name('client.blog.sreach');
Route::get('client/product/search', [ClientProductController::class,'search'])->name('client.product.search');


Route::get('client/product', [ClientProductController::class, 'home'])->name('client.home');
Route::post('client/product', [ClientProductController::class, 'homesort'])->name('client.home');
Route::get('client/product/details/{id}', [ClientProductController::class, 'product_details'])->name('client.product.details');
Route::post('client/product/details/reviews', [ClientProductController::class, 'reviews'])->name('reviews.store');
Route::post('client/product/comment', [ClientProductController::class, 'comment'])->name('client.product.comment');
Route::get('client/product/{category_id}', [ClientProductController::class, 'index'])->name('client.product');
Route::get('client/product/cart/{id}', [ClientProductController::class, 'addtocart'])->name('client.product.cart');
Route::delete('client/product/cart/remove-from-cart', [ClientProductController::class, 'remove'])->name('remove_from_cart');
Route::patch('client/product/cart/update-from-cart', [ClientProductController::class, 'update'])->name('update_from_cart');

Route::get('client/register', [LoginController::class, 'register'])->name('client.register');
Route::get('client/login', [LoginController::class, 'login'])->name('client.login');
Route::post('client/register', [LoginController::class, 'store_register'])->name('client.register.store');
Route::post('client/login', [LoginController::class, 'store_login'])->name('client.login.store');

Route::get('client/forget', [LoginController::class, 'forget'])->name('client.forget');
Route::post('client/forget', [LoginController::class, 'store_forget'])->name('client.forget.store');

Route::middleware(['checkLogin'])->group(function () {
    Route::get('client/checkout', [CheckOutController::class, 'index'])->name('check.out');
    Route::post('client/checkout', [CheckOutController::class, 'pay'])->name('pay');
    Route::get('done-payment-vnpay', [CheckOutController::class, 'donePaymentVnpay'])->name('done.payment.vnpay');
    Route::get('cancel-payment-paypal', [CheckOutController::class, 'cancelPaymentPaypal'])->name('cancel.payment.paypal');
    Route::get('done-payment-paypal/{id}', [CheckOutController::class, 'donePaymentPaypal'])->name('done.payment.paypal');
    Route::get('client/logout', [LoginController::class, 'logout'])->name('client.logout');
    Route::get('orders', [ClientOrders::class, 'index'])->name('client.orders');
    Route::get('order/id/{id}', [ClientOrders::class, 'show'])->name('client.order.detail');
    Route::get('product/id/{id}', [ClientOrders::class, 'showDetailProduct'])->name('client.product.detail');
    Route::get('client/check/email', [EmailController::class, 'checkemail'])->name('client.check.mail');
    Route::get('client/email', [EmailController::class, 'email'])->name('client.mail');
});
Auth::routes();
Route::get('/loginUser', function () {
    return view('logins.login');
})->name('loginUser');
Route::get('/registerUser', function () {
    return view('logins.register');
})->name('registerUser');
Route::post('/registerUser', [RegisterController::class, 'store'])->name('registerUser.store');
Route::post('/loginUser', [LoginUserController::class, 'store'])->name('loginUser.store');
Route::get('/logout', [LoginUserController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::prefix('administrator')->group(function () {
        Route::middleware('checkRole')->group(function () {
            Route::resource('user', UserController::class);
            Route::resource('role', RoleController::class);
            Route::resource('category', CategoryController::class);
            Route::resource('product', ProductController::class);
            Route::resource('videoproduct', VideoProductController::class);
            Route::resource('teacher', TeacherController::class);
            Route::resource('student', StudentController::class);
            Route::resource('order', OrderController::class);
            Route::resource('calendar', CalendarController::class);
            Route::resource('blog', BlogController::class);
            Route::resource('contact', ControllersContactController::class);
            Route::resource('discount', DiscountController::class);
        });
        Route::middleware('checkNotCustomer')->group(function () {
            Route::get('/', [MainController::class,'home'])->name('admin');
            Route::post('/', [MainController::class, 'index']);
        });
        Route::resource('class', ClassController::class);
    });
});

app/Models/Teacher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Teacher extends Model
{
    use HasFactory;

    protected $table ='teachers';

    protected $fillable =[
        'user_id',
        'name',
        'email',
        'address',
        'birth_date',
        'status',
        'phone',
        'level',
        'created_by',
        'updated_by'
    ];

    public function User():BelongsTo
    {
        return $this->belongsTo(User::class,'user_id','id');
    }
    public function getnumber()
    {
        return $this->count();
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Teacher\CreateTeacherRequest;
use App\Http\Requests\Teacher\UpdateTeacherRequest;
use App\Models\Teacher;
use App\Models\User;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    protected $teacher;
    public function __construct(Teacher $teacher)
    {
        $this->teacher = $teacher;
    }
    public function index()
    {
        $teachers = $this->teacher->paginate(5);
        return view('admin.teacher.index',compact('teachers'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $useremail = User::all();
        return view('admin.teacher.create',compact('useremail'));
    
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateTeacherRequest $request)
    {
    //    dd($request->all());
        $datacreate = $request->all();
        $teacher = $this->teacher->create($datacreate);
        return redirect()->route('teacher.index')->with(['message'=>'tạo giáo viên: '.$teacher->name.' thành công']);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $teacher = Teacher::find($id);
        $useremail = User::all();
        return view('admin.teacher.edit',compact('teacher','useremail'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateTeacherRequest $request, string $id)
    {
        // dd($request->all());
        $dataupdate = $request->all();
        $teacher = $this->teacher->findOrFail($id);
        $teacher->update($dataupdate);
        return redirect()->route('teacher.index')->with(['message'=>'Sửa giáo viên '.$teacher->name .' thành công']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Teacher::destroy($id);
        return to_route('teacher.index')->with(['message'=>'Xóa Thành Công']);
    
    }
    public function search(Request $request)
    {
        $searchText = $request->input('searchText');
        $blogs = Teacher::where('name', 'like', '%' . $searchText . '%')
                    ->orWhere('phone', 'like', '%' . $searchText . '%')
                    ->get();

        return view('admin.teacher.index', ['blogs' => $blogs]);
    }
}

resources/views/admin/teacher/create.blade.php
@extends('admin.layout.app')
@section('title', 'Thêm Giáo Viên')

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Teacher</li>
        </ol>
        <h6 class="font-weight-bolder mb-0"> Thêm Giáo Viên</h6>
    </nav>
@endsection


@section('content')
    <div class="card">


        <div>
            <h2>Thêm Giáo Viên</h2>
        </div>

        <div>
            <form action="{{ route('teacher.store') }}" method="POST">
                @csrf
                <div class="p-4">
                    <div class="input-group input-group-static mb-4">
                        <label>Tên</label>
                        <input type="text" value="{{ old('name') }}" name="name" class="form-control">
                        @error('name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Email Tài Khoản</label>
                        <select type="text" name="user_id" class="form-control">
                            <option value="">---Chọn---</option>
                            @foreach ($useremail as $item)
                                <option value="{{ $item->id }}">{{ $item->email }}</option>
                            @endforeach
                        </select>
                        @error('user_id')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Email</label>
                        <input type="email" value="{{ old('email') }}" name="email" placeholder="email"
                            class="form-control">

                        @error('email')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Địa Chỉ</label>
                        <input type="text" class="form-control @error('address') is-invalid @enderror" name="address">

                        @error('address')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Ngày Sinh</label>
                        <input type="date" value="{{ old('birth_date') }}" name="birth_date" class="form-control">

                        @error('birth_date')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Trạng Thái</label>
                        <select name="status" class="form-control">
                            <option>---Chọn---</option>
                            <option value="1">Có Lớp</option>
                            <option value="0">Không Có Lớp</option>

                        </select>
                        @error('status')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Điện Thoại</label>
                        <input type="tel" value="{{ old('phone') }}" name="phone" class="form-control">

                        @error('phone')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Trình Độ English</label>
                        <select name="level" class="form-control">
                            <option>---Chọn---</option>
                            <option value="C1">Tiếng Anh Bậc C1</option>
                            <option value="C2">Tiếng Anh Bậc B2</option>
                            <option value="Ielts trên 7.0">Ielts 7.0 trở lên</option>
                            <option value="Toeic Trên 700">Toeic 700 trở lên </option>
                        </select>
                        @error('cccd')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Người tạo</label>
                        <select name="created_by" class="form-control">
                            <option value="admin">Admin</option>
                            <option value="staff">Staff</option>


                        </select>

                        @error('created_by')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Người Cập Nhật</label>
                        <select name="updated_by" class="form-control">
                            <option value="admin">Admin</option>
                            <option value="staff">Staff</option>


                        </select>

                        @error('updated_by')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-submit btn-primary">Submit</button>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/teacher/edit.blade.php
@extends('admin.layout.app')
@section('title', 'Sửa Giáo Viên: ' . $teacher->name)

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Teacher</li>
        </ol>
        <h6 class="font-weight-bolder mb-0"> Sửa Giáo Viên</h6>
    </nav>
@endsection


@section('content')
    <div class="card">


        <div>
            <h2>Sửa Thông Tin Giáo Viên</h2>
        </div>

        <div>
            <form action="{{ route('teacher.update', $teacher->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="p-4">
                    <div class="input-group input-group-static mb-4">
                        <label>Tên</label>
                        <input type="text" value="{{ old('name') ?? $teacher->name }}" name="name"
                            class="form-control">
                        @error('name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Email Tài Khoản</label>
                        <select type="text" name="user_id" class="form-control">
                            <option value="">---Chọn---</option>
                            @foreach ($useremail as $item)
                                <option
                                    value="{{ $item->id }} {{ (old('user_id') ?? $teacher->User->email) == $item->id ? 'selected' : '' }}">
                                    {{ $item->email }}</option>
                            @endforeach
                        </select>
                        @error('user_id')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Email</label>
                        <input type="email" value="{{ old('email') ?? $teacher->email }}" name="email"
                            placeholder="email" class="form-control">

                        @error('email')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Địa Chỉ</label>
                        <input type="text" class="form-control @error('address') is-invalid @enderror" name="address"
                            value="{{ old('address') ?? $teacher->address }}">

                        @error('address')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Ngày Sinh</label>
                        <input type="date" value="{{ old('birth_date') ?? $teacher->birth_date }}" name="birth_date"
                            class="form-control">

                        @error('birth_date')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Trạng Thái</label>
                        <select name="status" class="form-control">
                            <option>---Chọn---</option>
                            <option value="1" {{ old('status', $teacher->status) == '1' ? 'selected' : '' }}>Có Lớp
                            </option>
                            <option value="0"{{ old('status', $teacher->status) == '0' ? 'selected' : '' }}>Không Có
                                Lớp</option>

                        </select>
                        @error('status')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Điện Thoại</label>
                        <input type="tel" value="{{ old('phone') ?? $teacher->phone }}" name="phone"
                            class="form-control">

                        @error('phone')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Trình Độ English</label>
                        <select name="level" class="form-control">
                            <option>---Chọn---</option>
                            <option value="C1" {{ old('level', $teacher->level) == 'C1' ? 'selected' : '' }}>Tiếng Anh
                                Bậc C1</option>
                            <option value="C2"{{ old('level', $teacher->level) == 'C2' ? 'selected' : '' }}>Tiếng Anh
                                Bậc B2</option>
                            <option
                                value="Ielts trên 7.0"{{ old('level', $teacher->level) == 'Ielts trên 7.0' ? 'selected' : '' }}>
                                Ielts 7.0 trở lên</option>
                            <option
                                value="Toeic Trên 700"{{ old('level', $teacher->level) == 'Toeic Trên 700' ? 'selected' : '' }}>
                                Toeic 700 trở lên </option>
                        </select>
                        @error('cccd')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Người tạo</label>
                        <select name="created_by" class="form-control">
                            <option>---chọn---</option>
                            <option value="admin"
                                {{ old('created_by', $teacher->created_by) == 'admin' ? 'selected' : '' }}>Admin</option>
                            <option value="staff"
                                {{ old('created_by', $teacher->created_by) == 'staff' ? 'selected' : '' }}>Staff</option>


                        </select>

                        @error('created_by')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Người Cập Nhật</label>
                        <select name="updated_by" class="form-control">
                            <option>---chọn---</option>
                            <option value="admin"
                                {{ old('updated_by', $teacher->updated_by) == 'admin' ? 'selected' : '' }}>Admin</option>
                            <option value="staff"
                                {{ old('updated_by', $teacher->updated_by) == 'staff' ? 'selected' : '' }}>Staff</option>


                        </select>

                        @error('updated_by')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>

                <button type="submit" class="btn btn-submit btn-primary">Submit</button>

            </form>

        </div>

    @endsection

resources/views/admin/teacher/index.blade.php
@extends('admin.layout.app')
@section('title','Giáo Viên')

@section('page')
 <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Teacher</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">Teacher</h6>
        </nav>
@endsection


@section('content')

<div class="card">
    @if(session('message'))
    <div> <h3 class="alert alert-success text-white">{{ session('message')}}</h3></div>
    @endif
<h1>
    Quản Lý Giáo Viên
</h1>
<div>
  <a style=" padding: 20px 25px;font-size: 20px;" href="{{route('teacher.create')}}" class="btn btn-primary">Thêm</a>
</div>
<div class="input-group input-group-outline my-3">
    <label class="form-label">Search</label>
    <input id="searchInput" type="text" class="form-control">
</div>
<div>
  <table class="table table-hover" style=" font-size: 1.4em; ">
      <tr>
          <th>#</th>
          <th>Tên</th>
          <th>Email Tài Khoản</th>
          <th>Email Cá Nhân</th>
          <th>Địa Chỉ</th>
          <th>Ngày Sinh</th>
          <th>Số Điện Thoại</th>
          <th>Trình Độ</th>
        
          <th>Action</th>
      </tr>
      @foreach ($teachers as $teacher)
          <tr>
              <td>{{$teacher ->id}}</td>
              <td>{{$teacher ->name}}</td>
              <td>{{$teacher ->User->email}}</td>
              <td>{{$teacher ->email}}</td>
              <td>{{$teacher ->address}}</td>
              <td>{{$teacher ->birth_date}}</td>
              <td>{{$teacher ->phone}}</td>
              <td>{{$teacher ->level}}</td>
             
              <td>
                  <a href="{{route('teacher.edit', $teacher->id)}}" class=" btn btn-warning btn-lg ">Edit</a>
                  
                  <form action="{{ route('teacher.destroy', $teacher->id)}}" method="post">
                  @csrf
                  @method('delete')
                      <button class=" btn btn-danger btn-lg ">Delete</button>
                  </form>
              </td>
          </tr>
      @endforeach
  </table>
  <div>
  {{ $teachers->links()}}
</div>
</div>

</div>

@endsection
@section('script')
<script>
    $(document).ready(function() {
        $('#searchInput').on('input', function() {
            var searchText = $(this).val().toLowerCase();
            $("table tbody tr").filter(function() {
                var title = $(this).find('td:eq(1)').text().toLowerCase();
                var name = $(this).find('td:eq(3)').text().toLowerCase();
                $(this).toggle(title.indexOf(searchText) > -1 || name.indexOf(searchText) > -1);
            });
        });
    });
</script>
@endsection