routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\Client\BlogViewController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\CheckOutController;
use App\Http\Controllers\Client\ClientProductController;
use App\Http\Controllers\Client\ContactController;
use App\Http\Controllers\Client\EmailController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\LoginController;
use App\Http\Controllers\Client\OrderController as ClientOrders;
use App\Http\Controllers\ContactController as ControllersContactController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\LoginUserController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VideoProductController;
use App\Http\Livewire\HeaderSearchComponent;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/client/cart', [HomeController::class, 'cart'])->name('client.cart');
Route::get('client/contact', [ContactController::class,'index'])->name('client.contact');
Route::post('client/contact', [ContactController::class,'store'])->name('client.contact');
Route::get('client/blog', [BlogViewController::class,'index'])->name('client.blog');
Route::get('client/blog/details/{id}', [BlogViewController::class, 'blog_details'])->name('client.blog.details');

Route::post('client/blog/sreach', [BlogViewController::class,'sreach'])->name('client.blog.sreach');
Route::get('client/product/search', [ClientProductController::class,'search'])->name('client.product.search');


Route::get('client/product', [ClientProductController::class, 'home'])->name('client.home');
Route::post('client/product', [ClientProductController::class, 'homesort'])->name('client.home');
Route::get('client/product/details/{id}', [ClientProductController::class, 'product_details'])->name('client.product.details');
Route::post('client/product/details/reviews', [ClientProductController::class, 'reviews'])->name('reviews.store');
Route::post('client/product/comment', [ClientProductController::class, 'comment'])->name('client.product.comment');
Route::get('client/product/{category_id}', [ClientProductController::class, 'index'])->name('client.product');
Route::get('client/product/cart/{id}', [ClientProductController::class, 'addtocart'])->name('client.product.cart');
Route::delete('client/product/cart/remove-from-cart', [ClientProductController::class, 'remove'])->name('remove_from_cart');
Route::patch('client/product/cart/update-from-cart', [ClientProductController::class, 'update'])->name('update_from_cart');

Route::get('client/register', [LoginController::class, 'register'])->name('client.register');
Route::get('client/login', [LoginController::class, 'login'])->name('client.login');
Route::post('client/register', [LoginController::class, 'store_register'])->name('client.register.store');
Route::post('client/login', [LoginController::class, 'store_login'])->name('client.login.store');

Route::get('client/forget', [LoginController::class, 'forget'])->name('client.forget');
Route::post('client/forget', [LoginController::class, 'store_forget'])->name('client.forget.store');

Route::middleware(['checkLogin'])->group(function () {
    Route::get('client/checkout', [CheckOutController::class, 'index'])->name('check.out');
    Route::post('client/checkout', [CheckOutController::class, 'pay'])->name('pay');
    Route::get('done-payment-vnpay', [CheckOutController::class, 'donePaymentVnpay'])->name('done.payment.vnpay');
    Route::get('cancel-payment-paypal', [CheckOutController::class, 'cancelPaymentPaypal'])->name('cancel.payment.paypal');
    Route::get('done-payment-paypal/{id}', [CheckOutController::class, 'donePaymentPaypal'])->name('done.payment.paypal');
    Route::get('client/logout', [LoginController::class, 'logout'])->name('client.logout');
    Route::get('orders', [ClientOrders::class, 'index'])->name('client.orders');
    Route::get('order/id/{id}', [ClientOrders::class, 'show'])->name('client.order.detail');
    Route::get('product/id/{id}', [ClientOrders::class, 'showDetailProduct'])->name('client.product.detail');
    Route::get('client/check/email', [EmailController::class, 'checkemail'])->name('client.check.mail');
    Route::get('client/email', [EmailController::class, 'email'])->name('client.mail');
});
Auth::routes();
Route::get('/loginUser', function () {
    return view('logins.login');
})->name('loginUser');
Route::get('/registerUser', function () {
    return view('logins.register');
})->name('registerUser');
Route::post('/registerUser', [RegisterController::class, 'store'])->name('registerUser.store');
Route::post('/loginUser', [LoginUserController::class, 'store'])->name('loginUser.store');
Route::get('/logout', [LoginUserController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::prefix('administrator')->group(function () {
        Route::middleware('checkRole')->group(function () {
            Route::resource('user', UserController::class);
            Route::resource('role', RoleController::class);
            Route::resource('category', CategoryController::class);
            Route::resource('product', ProductController::class);
            Route::resource('videoproduct', VideoProductController::class);
            Route::resource('teacher', TeacherController::class);
            Route::resource('student', StudentController::class);
            Route::resource('order', OrderController::class);
            Route::resource('calendar', CalendarController::class);
            Route::resource('blog', BlogController::class);
            Route::resource('contact', ControllersContactController::class);
            Route::resource('discount', DiscountController::class);
        });
        Route::middleware('checkNotCustomer')->group(function () {
            Route::get('/', [MainController::class,'home'])->name('admin');
            Route::post('/', [MainController::class, 'index']);
        });
        Route::resource('class', ClassController::class);
    });
});

app/Http/Controllers/ClassController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Classes\CreateClassRequest;
use App\Http\Requests\Classes\UpdateClassRequest;
use App\Models\Calendar;
use App\Models\Classes;
use App\Models\Product;
use App\Models\Teacher;
use Illuminate\Http\Request;
use Auth;

class ClassController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    protected $class;

    public function __construct(Classes $class)
    {
        $this->class = $class;
    }
    public function index()
    {
        $classes = $this->class->paginate(5);
        return view('admin.class.index',compact('classes'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {   
        if (Auth::user()->hasRole('Admin')) {
            $teacher = Teacher::all();
            $product = Product::all();
            $calendar = Calendar::all();
            return view('admin.class.create', compact('teacher','product','calendar'));
        } else {
            abort(403);
        }
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateClassRequest $request)
    {
        // dd($request->input());
        $datacreate = $request->all();
        $class = $this->class->create($datacreate);
        return redirect()->route('class.index')->with(['message'=>'tạo lớp: '.$class->name.' thành công']);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $class = Classes::find($id);
        $teacher = Teacher::all();
        $product = Product::all();
        $calendar = Calendar::all();
        return view('admin.class.edit',compact('class','teacher','product','calendar'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateClassRequest $request, string $id)
    {
        // dd($request->input());
        $dataupdate = $request->all();
        $class = $this->class->findOrFail($id);
        $class->update($dataupdate);
        return redirect()->route('class.index')->with(['message'=>'Sửa lớp '.$class->name .' thành công']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Classes::destroy($id);
        return to_route('class.index')->with(['message'=>'Xóa Thành Công']);
    
    }
    public function search(Request $request)
    {
        $searchText = $request->input('searchText');
        $blogs = Classes::where('name', 'like', '%' . $searchText . '%')
                    ->orWhere('code', 'like', '%' . $searchText . '%')
                    ->get();

        return view('admin.class.index', ['blogs' => $blogs]);
    }
}

resources/views/admin/class/create.blade.php
@extends('admin.layout.app')
@section('title', 'Tạo Lớp')

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Catogary</li>
        </ol>
        <h6 class="font-weight-bolder mb-0">Create Class</h6>
    </nav>
@endsection


@section('content')
    <div class="card">


        <div>
            <h2>Tạo Lớp</h2>
        </div>

        <div>
            <form action="{{ route('class.store') }}" method="POST">
                @csrf
                <div class="p-4">
                    <div class="input-group input-group-static mb-4">
                        <label>Tên Lớp</label>
                        <input type="text" value="{{ old('name') }}" name="name" class="form-control">
                        @error('name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Mã Lớp</label>
                        <input type="text" value="{{ old('code') }}" name="code" class="form-control"
                            placeholder="P-Number">
                        @error('code')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Trạng Thái</label>
                        <select name="status" class="form-control">
                            <option>---Chọn---</option>
                            <option value="Active">Active</option>
                            <option value="Close">Close</option>


                        </select>

                        @error('status')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>


                    <div class="input-group input-group-static mb-4">
                        <label>Mô tả</label>
                        <input type="text" value="{{ old('description') }}" name="description" placeholder="Mô tả"
                            class="form-control">

                        @error('description')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>


                    <div class="input-group input-group-static mb-4">
                        <label>Số tiết học</label>
                        <input type="phone" value="{{ old('sessions_number') }}" name="sessions_number"
                            class="form-control">

                        @error('sessions_number')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Lịch Học</label>
                        <select type="text" name="calendar_id" class="form-control">
                            <option>---chọn----</option>
                            @foreach ($calendar as $item)
                                <option value="{{ $item->id }}">{{ $item->lesson }}</option>
                            @endforeach
                        </select>
                        @error('calendar_id')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Giáo Viên</label>
                        <select type="text" name="teacher_id" class="form-control">
                            <option>---chọn----</option>
                            @foreach ($teacher as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                        @error('teacher_id')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Khóa Học</label>
                        <select type="text" name="product_id" class="form-control">
                            <option>---chọn----</option>
                            @foreach ($product as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                        @error('product_id')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Số Lượng Học Viên</label>
                        <input type="phone" value="{{ old('quantity') }}" name="quantity" placeholder=""
                            class="form-control">

                        @error('quantity')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Ngày bắt đầu</label>
                        <input type="date" name="start_date" placeholder="" class="form-control">

                        @error('start_date')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Ngày Kết Thúc</label>
                        <input type="date" name="end_date" placeholder="" class="form-control">

                        @error('end_date')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>


                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Người Tạo</label>
                        <select name="created_by" class="form-control">
                            <option>---Chọn---</option>
                            <option value="Admin">Admin</option>
                            <option value="Staff">Staff</option>
                            <option value="Other">Other</option>

                        </select>

                        @error('created_by')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Người Cập Nhật</label>
                        <select name="updated_by" class="form-control">
                            <option>---Chọn---</option>
                            <option value="Admin">Admin</option>
                            <option value="Staff">Staff</option>
                            <option value="Other">Other</option>

                        </select>

                        @error('update_by')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                </div>
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/class/edit.blade.php
@extends('admin.layout.app')
@section('title', 'Tạo Lớp ' . $class->name)

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Catogary</li>
        </ol>
        <h6 class="font-weight-bolder mb-0">Edit Class</h6>
    </nav>
@endsection


@section('content')
    <div class="card">


        <div>
            <h2>Sửa Lớp</h2>
        </div>

        <div>
            <form action="{{ route('class.update', $class->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="p-4">
                    <div class="input-group input-group-static mb-4">
                        <label>Tên Lớp</label>
                        <input type="text" value="{{ old('name') ?? $class->name }}" name="name" class="form-control">
                        @error('name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Mã Lớp</label>
                        <input type="text" value="{{ old('code') ?? $class->code }}" name="code" class="form-control"
                            placeholder="P-Number">
                        @error('code')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Trạng Thái</label>
                        <select name="status" class="form-control">
                            <option>---Chọn---</option>
                            <option value="Active" {{ old('status', $class->status) == 'Active' ? 'selected' : '' }}>Active
                            </option>
                            <option value="Close" {{ old('status', $class->status) == 'Close' ? 'selected' : '' }}>Close
                            </option>


                        </select>

                        @error('status')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>


                    <div class="input-group input-group-static mb-4">
                        <label>Mô tả</label>
                        <input type="text" value="{{ old('description') ?? $class->description }}" name="description"
                            placeholder="Mô tả" class="form-control">

                        @error('description')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>


                    <div class="input-group input-group-static mb-4">
                        <label>Số tiết học</label>
                        <input type="phone" value="{{ old('sessions_number') ?? $class->sessions_number }}"
                            name="sessions_number" class="form-control">

                        @error('sessions_number')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Lịch Học</label>
                        <select type="text" name="calendar_id" class="form-control">
                            <option>---chọn----</option>
                            @foreach ($calendar as $item)
                                <option value="{{ $item->id }}"
                                    {{ $class->calendar_id == $item->id ? 'selected' : '' }}>
                                    {{ $item->lesson }}</option>
                            @endforeach
                        </select>
                        @error('calendar_id')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Giáo Viên</label>
                        <select type="text" name="teacher_id" class="form-control">
                            <option>---chọn----</option>
                            @foreach ($teacher as $item)
                                <option value="{{ $item->id }}"
                                    {{ $class->teacher_id == $item->id ? 'selected' : '' }}>
                                    {{ $item->name }}</option>
                            @endforeach
                        </select>
                        @error('teacher_id')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Khóa Học</label>
                        <select type="text" name="product_id" class="form-control">
                            <option>---chọn----</option>
                            @foreach ($product as $item)
                                <option value="{{ $item->id }}"
                                    {{ $class->product_id == $item->id ? 'selected' : '' }}>
                                    {{ $item->name }}</option>
                            @endforeach
                        </select>
                        @error('product_id')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Số Lượng Học Viên</label>
                        <input type="phone" value="{{ old('quantity') ?? $class->quantity }}" name="quantity"
                            placeholder="" class="form-control">

                        @error('quantity')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Ngày bắt đầu</label>
                        <input type="date" value="{{ old('start_date', $class->start_date) }}" name="start_date"
                            placeholder="" class="form-control">

                        @error('start_date')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Ngày Kết Thúc</label>
                        <input type="date" value="{{ old('end_date', $class->end_date) }}" name="end_date"
                            placeholder="" class="form-control">

                        @error('end_date')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>


                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Người Tạo</label>
                        <select name="created_by" class="form-control">
                            <option>---Chọn---</option>
                            <option value="Admin"
                                {{ old('created_by', $class->created_by) == 'Admin' ? 'selected' : '' }}>
                                Admin</option>
                            <option value="Staff"
                                {{ old('created_by', $class->created_by) == 'Staff' ? 'selected' : '' }}>
                                Staff</option>
                            <option value="Other"
                                {{ old('created_by', $class->created_by) == 'Other' ? 'selected' : '' }}>
                                Other</option>

                        </select>

                        @error('created_by')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Người Cập Nhật</label>
                        <select name="updated_by" class="form-control">
                            <option>---Chọn---</option>
                            <option value="Admin"
                                {{ old('updated_by', $class->updated_by) == 'Admin' ? 'selected' : '' }}>
                                Admin</option>
                            <option value="Staff"
                                {{ old('updated_by', $class->updated_by) == 'Staff' ? 'selected' : '' }}>
                                Staff</option>
                            <option value="Other"
                                {{ old('updated_by', $class->updated_by) == 'Other' ? 'selected' : '' }}>
                                Other</option>

                        </select>

                        @error('update_by')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                </div>
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/class/index.blade.php
@extends('admin.layout.app')
@section('title', 'Lớp Học')

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Class</li>
        </ol>
        <h6 class="font-weight-bolder mb-0">Class</h6>
    </nav>
@endsection


@section('content')
    <div class="card">
        @if (session('message'))
            <div>
                <h3 class="alert alert-success text-white">{{ session('message') }}</h3>
            </div>
        @endif
        <h1>
            Lớp Học
        </h1>
        @if (Auth::user()->hasRole('Admin'))
            <div>
                <a style=" padding: 20px 25px; font-size: 20px;" href="{{ route('class.create') }}"
                    class="btn btn-primary">Thêm</a>
            </div>
        @endif
        <div class="input-group input-group-outline my-3">
            <label class="form-label">Search</label>
            <input id="searchInput" type="text" class="form-control">
        </div>
        <div>
            <table class="table table-hover" style=" font-size: 1.4em; ">
                <tr>
                    <th>#</th>
                    <th>Tên lớp học</th>
                    <th>Mã lớp</th>
                    <th>Trạng thái</th>
                    <th>Mô tả</th>
                    <th>Số buổi học</th>
                    <th>Lịch Học</th>
                    <th>Giáo viên</th>
                    <th>Khóa học</th>
                    <th>Số lượng học viên</th>
                    <th>Thời gian bắt đầu</th>
                    <th>Thời gian kết thúc</th>
                    @if (Auth::user()->hasRole('Admin'))
                        <th>Action</th>
                    @endif
                </tr>
                @foreach ($classes as $class)
                    <tr>
                        <td>{{ $class->id }}</td>
                        <td>{{ $class->name }}</td>
                        <td>{{ $class->code }}</td>
                        <td>{{ $class->status }}</td>
                        <td>{{ $class->description }}</td>
                        <td>{{ $class->sessions_number }}</td>
                        <td>{{ $class->Calendar->lesson }}</td>
                        <td>{{ $class->Teacher->name }}</td>
                        <td>{{ $class->Product->name }}</td>
                        <td>{{ $class->quantity }}</td>
                        <td>{{ $class->start_date }}</td>
                        <td>{{ $class->end_date }}</td>
                        <td>
                            @if (Auth::user()->hasRole('Admin'))
                                <a href="{{ route('class.edit', $class->id) }}" class=" btn btn-warning btn-lg ">Edit</a>

                                <form action="{{ route('class.destroy', $class->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button class=" btn btn-danger btn-lg ">Delete</button>
                                </form>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </table>
            <div>
                {{ $classes->links() }}
            </div>
        </div>

    </div>
@endsection
@section('script')
<script>
    $(document).ready(function() {
        $('#searchInput').on('input', function() {
            var searchText = $(this).val().toLowerCase();
            $("table tbody tr").filter(function() {
                var title = $(this).find('td:eq(1)').text().toLowerCase();
                var name = $(this).find('td:eq(3)').text().toLowerCase();
                $(this).toggle(title.indexOf(searchText) > -1 || name.indexOf(searchText) > -1);
            });
        });
    });
</script>
@endsection