routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\Client\BlogViewController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\CheckOutController;
use App\Http\Controllers\Client\ClientProductController;
use App\Http\Controllers\Client\ContactController;
use App\Http\Controllers\Client\EmailController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\LoginController;
use App\Http\Controllers\Client\OrderController as ClientOrders;
use App\Http\Controllers\ContactController as ControllersContactController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\LoginUserController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VideoProductController;
use App\Http\Livewire\HeaderSearchComponent;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/client/cart', [HomeController::class, 'cart'])->name('client.cart');
Route::get('client/contact', [ContactController::class,'index'])->name('client.contact');
Route::post('client/contact', [ContactController::class,'store'])->name('client.contact');
Route::get('client/blog', [BlogViewController::class,'index'])->name('client.blog');
Route::get('client/blog/details/{id}', [BlogViewController::class, 'blog_details'])->name('client.blog.details');

Route::post('client/blog/sreach', [BlogViewController::class,'sreach'])->name('client.blog.sreach');
Route::get('client/product/search', [ClientProductController::class,'search'])->name('client.product.search');


Route::get('client/product', [ClientProductController::class, 'home'])->name('client.home');
Route::post('client/product', [ClientProductController::class, 'homesort'])->name('client.home');
Route::get('client/product/details/{id}', [ClientProductController::class, 'product_details'])->name('client.product.details');
Route::post('client/product/details/reviews', [ClientProductController::class, 'reviews'])->name('reviews.store');
Route::post('client/product/comment', [ClientProductController::class, 'comment'])->name('client.product.comment');
Route::get('client/product/{category_id}', [ClientProductController::class, 'index'])->name('client.product');
Route::get('client/product/cart/{id}', [ClientProductController::class, 'addtocart'])->name('client.product.cart');
Route::delete('client/product/cart/remove-from-cart', [ClientProductController::class, 'remove'])->name('remove_from_cart');
Route::patch('client/product/cart/update-from-cart', [ClientProductController::class, 'update'])->name('update_from_cart');

Route::get('client/register', [LoginController::class, 'register'])->name('client.register');
Route::get('client/login', [LoginController::class, 'login'])->name('client.login');
Route::post('client/register', [LoginController::class, 'store_register'])->name('client.register.store');
Route::post('client/login', [LoginController::class, 'store_login'])->name('client.login.store');

Route::get('client/forget', [LoginController::class, 'forget'])->name('client.forget');
Route::post('client/forget', [LoginController::class, 'store_forget'])->name('client.forget.store');

Route::middleware(['checkLogin'])->group(function () {
    Route::get('client/checkout', [CheckOutController::class, 'index'])->name('check.out');
    Route::post('client/checkout', [CheckOutController::class, 'pay'])->name('pay');
    Route::get('done-payment-vnpay', [CheckOutController::class, 'donePaymentVnpay'])->name('done.payment.vnpay');
    Route::get('cancel-payment-paypal', [CheckOutController::class, 'cancelPaymentPaypal'])->name('cancel.payment.paypal');
    Route::get('done-payment-paypal/{id}', [CheckOutController::class, 'donePaymentPaypal'])->name('done.payment.paypal');
    Route::get('client/logout', [LoginController::class, 'logout'])->name('client.logout');
    Route::get('orders', [ClientOrders::class, 'index'])->name('client.orders');
    Route::get('order/id/{id}', [ClientOrders::class, 'show'])->name('client.order.detail');
    Route::get('product/id/{id}', [ClientOrders::class, 'showDetailProduct'])->name('client.product.detail');
    Route::get('client/check/email', [EmailController::class, 'checkemail'])->name('client.check.mail');
    Route::get('client/email', [EmailController::class, 'email'])->name('client.mail');
});
Auth::routes();
Route::get('/loginUser', function () {
    return view('logins.login');
})->name('loginUser');
Route::get('/registerUser', function () {
    return view('logins.register');
})->name('registerUser');
Route::post('/registerUser', [RegisterController::class, 'store'])->name('registerUser.store');
Route::post('/loginUser', [LoginUserController::class, 'store'])->name('loginUser.store');
Route::get('/logout', [LoginUserController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::prefix('administrator')->group(function () {
        Route::middleware('checkRole')->group(function () {
            Route::resource('user', UserController::class);
            Route::resource('role', RoleController::class);
            Route::resource('category', CategoryController::class);
            Route::resource('product', ProductController::class);
            Route::resource('videoproduct', VideoProductController::class);
            Route::resource('teacher', TeacherController::class);
            Route::resource('student', StudentController::class);
            Route::resource('order', OrderController::class);
            Route::resource('calendar', CalendarController::class);
            Route::resource('blog', BlogController::class);
            Route::resource('contact', ControllersContactController::class);
            Route::resource('discount', DiscountController::class);
        });
        Route::middleware('checkNotCustomer')->group(function () {
            Route::get('/', [MainController::class,'home'])->name('admin');
            Route::post('/', [MainController::class, 'index']);
        });
        Route::resource('class', ClassController::class);
    });
});

app/Models/Calendar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Calendar extends Model
{
    use HasFactory;
    
    protected $table = 'calendars';

    protected $fillable = [
       'lesson',
       'description'
    ];
}

app/Http/Controllers/CalendarController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Calendar\CreateCalendarRequest;
use App\Models\Calendar;
use Illuminate\Http\Request;

class CalendarController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    protected $calendar;

    public function __construct(Calendar $calendar)
    {
        $this->calendar = $calendar;
    }
    public function index()
    {
        $calendars = $this->calendar->paginate(5);
        return view('admin.calendar.index',compact('calendars'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $calendars = $this->calendar->all();
        return view('admin.calendar.create',compact('calendars'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateCalendarRequest $request)
    {
        // dd($request->all());
        $data = $request->all();
        $calendar = Calendar::create($data);
        return redirect()->route('calendar.index')->with(['message'=>'Tạo lịch học '.$calendar->lesson." thành công"]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $calendar = $this->calendar->findOrfail($id);
        return view('admin.calendar.edit', compact('calendar'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        // dd($request->all());
        $dataupdate = $request->all();
        $calendar = $this->calendar->findOrFail($id);
        $calendar->update($dataupdate);
        return redirect()->route('calendar.index')->with(['message'=>'Sửa lịch học '.$calendar->lesson .' thành công']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Calendar::destroy($id);
        return to_route('calendar.index')->with(['message'=>'Xóa Thành Công']);
    }
    public function search(Request $request)
    {
        $searchText = $request->input('searchText');
        $blogs = Calendar::where('lesson', 'like', '%' . $searchText . '%')
                    ->get();

        return view('admin.calendar.index', ['blogs' => $blogs]);
    }
}

resources/views/admin/calendar/create.blade.php
@extends('admin.layout.app')
@section('title', 'Tạo Lịch Học')

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Calendar</li>
        </ol>
        <h6 class="font-weight-bolder mb-0">Create Calendar</h6>
    </nav>
@endsection


@section('content')
    <div class="card">


        <div>
            <h2>Tạo Lịch Học</h2>
        </div>

        <div>
            <form action="{{ route('calendar.store') }}" method="POST">
                @csrf
                <div class="p-4">
                    <div class="input-group input-group-static mb-4">
                        <label>Tên Lịch Học</label>
                        <input type="text" value="{{ old('lesson') }}" name="lesson" class="form-control">
                        @error('lesson')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Mô Tả Lịch Học</label>
                        <input type="text" value="{{ old('description') }}" name="description" class="form-control">
                        @error('description')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>


                </div>
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/calendar/edit.blade.php
@extends('admin.layout.app')
@section('title', 'Sửa Lịch Học' . $calendar->lesson)

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Calendar</li>
        </ol>
        <h6 class="font-weight-bolder mb-0">Edit Calendar</h6>
    </nav>
@endsection


@section('content')
    <div class="card">


        <div>
            <h2>Sửa Lịch Học</h2>
        </div>

        <div>
            <form action="{{ route('calendar.update', $calendar->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="p-4">
                    <div class="input-group input-group-static mb-4">
                        <label>Tên Lịch Học</label>
                        <input type="text" value="{{ old('lesson') ?? $calendar->lesson }}" name="lesson"
                            class="form-control">
                        @error('lesson')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Mô Tả Lịch Học</label>
                        <input type="text" value="{{ old('description') ?? $calendar->description }}" name="description"
                            class="form-control">
                        @error('description')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>


                </div>
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/calendar/index.blade.php
@extends('admin.layout.app')
@section('title', 'Lịch Học')

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Calendar</li>
        </ol>
        <h6 class="font-weight-bolder mb-0">Calendar</h6>
    </nav>
@endsection

@section('content')
    <div class="card">
        @if (session('message'))
            <div>
                <h3 class="alert alert-success text-white">{{ session('message') }}</h3>
            </div>
        @endif
        <h1>
            Lịch Học
        </h1>
        <div>
            <a style=" padding: 20px 25px; font-size: 20px;" href="{{ route('calendar.create') }}"
                class="btn btn-primary">Thêm</a>
        </div>
        <div class="input-group input-group-outline my-3">
            <label class="form-label">Search</label>
            <input id="searchInput" type="text" class="form-control">
        </div>
        <div>
            <table class="table table-hover" style=" font-size: 1.4em; ">
                <tr>
                    <th>#</th>
                    <th>Buổi học</th>
                    <th>Mô Tả</th>
                    <th>Action</th>
                </tr>
                @foreach ($calendars as $calendar)
                    <tr>
                        <td>{{ $calendar->id }}</td>
                        <td>{{ $calendar->lesson }}</td>
                        <td>{{ $calendar->description }}</td>

                        <td>
                            <a href="{{ route('calendar.edit', $calendar->id) }}" class=" btn btn-warning btn-lg ">Edit</a>

                            <form action="{{ route('calendar.destroy', $calendar->id) }}" method="post">
                                @csrf
                                @method('delete')
                                <button class=" btn btn-danger btn-lg ">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </table>
            <div>
                {{ $calendars->links() }}
            </div>
        </div>

    </div>
@endsection
@section('script')
    <script>
        $(document).ready(function() {
            $('#searchInput').on('input', function() {
                var searchText = $(this).val().toLowerCase();
                $("table tbody tr").filter(function() {
                    var title = $(this).find('td:eq(1)').text().toLowerCase();
                    var name = $(this).find('td:eq(3)').text().toLowerCase();
                    $(this).toggle(title.indexOf(searchText) > -1 || name.indexOf(searchText) > -1);
                });
            });
        });
    </script>
@endsection