routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\Client\BlogViewController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\CheckOutController;
use App\Http\Controllers\Client\ClientProductController;
use App\Http\Controllers\Client\ContactController;
use App\Http\Controllers\Client\EmailController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\LoginController;
use App\Http\Controllers\Client\OrderController as ClientOrders;
use App\Http\Controllers\ContactController as ControllersContactController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\LoginUserController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VideoProductController;
use App\Http\Livewire\HeaderSearchComponent;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/client/cart', [HomeController::class, 'cart'])->name('client.cart');
Route::get('client/contact', [ContactController::class,'index'])->name('client.contact');
Route::post('client/contact', [ContactController::class,'store'])->name('client.contact');
Route::get('client/blog', [BlogViewController::class,'index'])->name('client.blog');
Route::get('client/blog/details/{id}', [BlogViewController::class, 'blog_details'])->name('client.blog.details');

Route::post('client/blog/sreach', [BlogViewController::class,'sreach'])->name('client.blog.sreach');
Route::get('client/product/search', [ClientProductController::class,'search'])->name('client.product.search');


Route::get('client/product', [ClientProductController::class, 'home'])->name('client.home');
Route::post('client/product', [ClientProductController::class, 'homesort'])->name('client.home');
Route::get('client/product/details/{id}', [ClientProductController::class, 'product_details'])->name('client.product.details');
Route::post('client/product/details/reviews', [ClientProductController::class, 'reviews'])->name('reviews.store');
Route::post('client/product/comment', [ClientProductController::class, 'comment'])->name('client.product.comment');
Route::get('client/product/{category_id}', [ClientProductController::class, 'index'])->name('client.product');
Route::get('client/product/cart/{id}', [ClientProductController::class, 'addtocart'])->name('client.product.cart');
Route::delete('client/product/cart/remove-from-cart', [ClientProductController::class, 'remove'])->name('remove_from_cart');
Route::patch('client/product/cart/update-from-cart', [ClientProductController::class, 'update'])->name('update_from_cart');

Route::get('client/register', [LoginController::class, 'register'])->name('client.register');
Route::get('client/login', [LoginController::class, 'login'])->name('client.login');
Route::post('client/register', [LoginController::class, 'store_register'])->name('client.register.store');
Route::post('client/login', [LoginController::class, 'store_login'])->name('client.login.store');

Route::get('client/forget', [LoginController::class, 'forget'])->name('client.forget');
Route::post('client/forget', [LoginController::class, 'store_forget'])->name('client.forget.store');

Route::middleware(['checkLogin'])->group(function () {
    Route::get('client/checkout', [CheckOutController::class, 'index'])->name('check.out');
    Route::post('client/checkout', [CheckOutController::class, 'pay'])->name('pay');
    Route::get('done-payment-vnpay', [CheckOutController::class, 'donePaymentVnpay'])->name('done.payment.vnpay');
    Route::get('cancel-payment-paypal', [CheckOutController::class, 'cancelPaymentPaypal'])->name('cancel.payment.paypal');
    Route::get('done-payment-paypal/{id}', [CheckOutController::class, 'donePaymentPaypal'])->name('done.payment.paypal');
    Route::get('client/logout', [LoginController::class, 'logout'])->name('client.logout');
    Route::get('orders', [ClientOrders::class, 'index'])->name('client.orders');
    Route::get('order/id/{id}', [ClientOrders::class, 'show'])->name('client.order.detail');
    Route::get('product/id/{id}', [ClientOrders::class, 'showDetailProduct'])->name('client.product.detail');
    Route::get('client/check/email', [EmailController::class, 'checkemail'])->name('client.check.mail');
    Route::get('client/email', [EmailController::class, 'email'])->name('client.mail');
});
Auth::routes();
Route::get('/loginUser', function () {
    return view('logins.login');
})->name('loginUser');
Route::get('/registerUser', function () {
    return view('logins.register');
})->name('registerUser');
Route::post('/registerUser', [RegisterController::class, 'store'])->name('registerUser.store');
Route::post('/loginUser', [LoginUserController::class, 'store'])->name('loginUser.store');
Route::get('/logout', [LoginUserController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::prefix('administrator')->group(function () {
        Route::middleware('checkRole')->group(function () {
            Route::resource('user', UserController::class);
            Route::resource('role', RoleController::class);
            Route::resource('category', CategoryController::class);
            Route::resource('product', ProductController::class);
            Route::resource('videoproduct', VideoProductController::class);
            Route::resource('teacher', TeacherController::class);
            Route::resource('student', StudentController::class);
            Route::resource('order', OrderController::class);
            Route::resource('calendar', CalendarController::class);
            Route::resource('blog', BlogController::class);
            Route::resource('contact', ControllersContactController::class);
            Route::resource('discount', DiscountController::class);
        });
        Route::middleware('checkNotCustomer')->group(function () {
            Route::get('/', [MainController::class,'home'])->name('admin');
            Route::post('/', [MainController::class, 'index']);
        });
        Route::resource('class', ClassController::class);
    });
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'address',
        'cccd',
        'birth_date',
        'gender',
        'type'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function Oder():HasMany
    {
        return $this->hasMany(Oder::class,'user_id','id');
    }

    public function Teacher():HasOne
    {
        return $this->hasOne(Teacher::class,'user_id','id');

    }
    public function Student():HasOne
    {
        return $this->hasOne(Student::class,'user_id','id');
        
    }
    public function isAdmin()
    {
        return $this->type === 'Admin'; 
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    protected $user;
    protected $role;
    public function __construct(User $user, Role $role)
    {
        $this->user = $user;
        $this->role = $role;
    }
    public function index()
    {
        $users = $this->user->paginate(16);
        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $roles = $this->role->all()->groupBy('name');
        return view('admin.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateUserRequest $request)
    {
        $datacreate =$request->all();
        
        $datacreate['password'] = Hash::make($request->password);

        $user = $this->user->create($datacreate);
        $user->roles()->attach($datacreate['role_id' ?? []]);
        return to_route('user.index')->with(['message'=>'tạo thành công']);
    }

   

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $user = $this->user->findOrfail($id)->load('roles');
        $roles = $this->role->all()->groupBy('name');
        return view('admin.user.edit', compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateUserRequest $request, string $id)
    {
        $user = $this->user->findOrfail($id)->load('roles');
        $dataupdate =$request->except('password');
        if($request->password)
        {
            $dataupdate['password'] = Hash::make($request->password);
        }
       
        $user->update($dataupdate);
        $user->roles()->sync($dataupdate['role_id'] ?? []);
        return to_route('user.index')->with(['message'=>'sửa thành công']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
       
        User::destroy($id);
        return to_route('user.index')->with(['message'=>'Xóa Thành Công']);
   
    }
    public function search(Request $request)
    {
        $searchText = $request->input('searchText');
        $blogs = User::where('name', 'like', '%' . $searchText . '%')
                    ->orWhere('phone', 'like', '%' . $searchText . '%')
                    ->get();

        return view('admin.user.index', ['blogs' => $blogs]);
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layout.app')
@section('title', 'Tạo Người Dùng')

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">User</li>
        </ol>
        <h6 class="font-weight-bolder mb-0"> Tạo Người Dùng</h6>
    </nav>
@endsection


@section('content')
    <div class="card">


        <div>
            <h2>Tạo Người dùng</h2>
        </div>

        <div>
            <form action="{{ route('user.store') }}" method="POST">
                @csrf
                <div class="p-4">
                    <div class="input-group input-group-static mb-4">
                        <label>Tên</label>
                        <input type="text" value="{{ old('name') }}" name="name" class="form-control">
                        @error('name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Email</label>
                        <input type="email" value="{{ old('email') }}" name="email" placeholder="email"
                            class="form-control">

                        @error('email')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Mật Khẩu</label>
                        <input type="password" class="form-control @error('password') is-invalid @enderror" name="password"
                            placeholder="Mật khẩu">

                        @error('password')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Điện Thoại</label>
                        <input type="tel" value="{{ old('phone') }}" name="phone" class="form-control">

                        @error('phone')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Địa Chỉ</label>
                        <input type="text" value="{{ old('address') }}" name="address" class="form-control">

                        @error('address')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Căn Cước Công Dân</label>
                        <input type="tel" value="{{ old('cccd') }}" name="cccd" class="form-control">

                        @error('cccd')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Ngày Sinh</label>
                        <input type="date" value="{{ old('birth_date') }}" name="birth_date" class="form-control">

                        @error('birth_date')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Loại Người Dùng</label>
                        <select name="type" class="form-control">
                            <option value="">---Chọn---</option>
                            <option value="Admin">Quản Trị Viên</option>
                            <option value="Student">Học Viên</option>
                            <option value="Teacher">Giáo Viên</option>
                            <option value="Client">Khách Hàng</option>
                        </select>

                        @error('type')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Gender</label>
                        <select name="gender" class="form-control">
                            <option value="Nam">Nam</option>
                            <option value="Nữ">Nữ</option>
                            <option value="Khác">Khác</option>

                        </select>

                        @error('gender')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <label for=""> Vai Trò Người Dùng</label>
                    @foreach ($roles as $groupName => $role)
                        <div class="col-6">
                            <h4>{{ $groupName }}</h4>

                            <div>
                                @foreach ($role as $item)
                                    <div class="form-check">
                                        <input class="form-check-input" name="role_id[]" type="checkbox"
                                            value="{{ $item->id }}">
                                        <label class="custom-control-label"
                                            for="customCheck1">{{ $item->display_name }}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    @endforeach
                </div>
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layout.app')
@section('title', 'sửa Người Dùng' . $user->name)

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">User</li>
        </ol>
        <h6 class="font-weight-bolder mb-0"> Sửa Người Dùng</h6>
    </nav>
@endsection


@section('content')
    <div class="card">


        <div>
            <h2>Sửa Người dùng</h2>
        </div>

        <div>
            <form action="{{ route('user.update', $user->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="p-4">
                    <div class="input-group input-group-static mb-4">
                        <label>Tên</label>
                        <input type="text" value="{{ old('name') ?? $user->name }} " name="name" class="form-control">
                        @error('name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror

                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Email</label>
                        <input type="email" value="{{ old('email') ?? $user->email }}" name="email" placeholder="email"
                            class="form-control">

                        @error('email')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label for="password">Mật khẩu</label>
                        <input type="password" name="password" id="password"
                            class="form-control @error('password') is-invalid @enderror" value="{{ old('password') }}"
                            placeholder="Mật khẩu">

                        @error('password')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror


                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Điện Thoại</label>
                        <input type="tel" value="{{ old('phone') ?? $user->phone }}" name="phone"
                            class="form-control">

                        @error('phone')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Địa Chỉ</label>
                        <input type="text" value="{{ old('address') ?? $user->address }}" name="address"
                            class="form-control">

                        @error('address')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Căn Cước Công Dân</label>
                        <input type="tel" value="{{ old('cccd') ?? $user->cccd }}" name="cccd" class="form-control">

                        @error('cccd')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Ngày Sinh</label>
                        <input type="date" value="{{ old('birth_date', date('Y-m-d')) }}" name="birth_date"
                            class="form-control">

                        @error('birth_date')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Loại Người Dùng</label>
                        <select name="type" class="form-control" value="{{ $user->type }}">
                            <option value="Admin">---Chọn---</option>
                            <option value="Admin" {{ old('type', $user->type) == 'Admin' ? 'selected' : '' }}>Quản Trị
                                Viên
                            </option>
                            <option value="Student" {{ old('type', $user->type) == 'Student' ? 'selected' : '' }}>Học Viên
                            </option>
                            <option value="Teacher" {{ old('type', $user->type) == 'Teacher' ? 'selected' : '' }}>Giáo Viên
                            </option>
                            <option value="Client" {{ old('type', $user->type) == 'Client' ? 'selected' : '' }}>Khách Hàng
                            </option>

                        </select>

                        @error('type')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label class="ms-0">Gender</label>
                        <select name="gender" class="form-control" value="{{ $user->gender }}">
                            <option>Nam</option>
                            <option>Nữ</option>
                            <option>Khác</option>

                        </select>

                        @error('gender')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <label for=""> Vai Trò Người Dùng</label>
                    @foreach ($roles as $groupName => $role)
                        <div class="col-6">
                            <h4>{{ $groupName }}</h4>

                            <div>
                                @foreach ($role as $item)
                                    <div class="form-check">
                                        <input class="form-check-input" name="role_id[]"
                                            {{ $user->roles->contains('id', $item->id) ? 'checked' : '' }} type="checkbox"
                                            value="{{ $item->id }}">
                                        <label class="custom-control-label"
                                            for="customCheck1">{{ $item->display_name }}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    @endforeach

                </div>
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layout.app')
@section('title', 'User')

@section('page')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">User</li>
        </ol>
        <h6 class="font-weight-bolder mb-0">Teacher</h6>
    </nav>
@endsection


@section('content')
    <div class="card">
        @if (session('message'))
            <div>
                <h3 class="alert alert-success text-white">{{ session('message') }}</h3>
            </div>
        @endif
        <h1>
            User
        </h1>
        <div>
            <a style=" padding: 20px 25px; font-size: 20px;" href="{{ route('user.create') }}"
                class="btn btn-primary">Thêm</a>
        </div>
        <div class="input-group input-group-outline my-3">
            <label class="form-label">Search</label>
            <input id="searchInput" type="text" class="form-control">
        </div>
        <div>
            <table class="table table-hover" style=" font-size: 1.4em; ">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>CCCD</th>
                    <th>Birth Date</th>
                    <th>Gender</th>
                    <th>Type</th>
                    <th>Action</th>
                </tr>
                @foreach ($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->phone }}</td>
                        <td>{{ $user->address }}</td>
                        <td>{{ $user->cccd }}</td>
                        <td>{{ $user->birth_date }}</td>
                        <td>{{ $user->gender }}</td>
                        <td>{{ $user->type }}</td>
                        <td>
                            <a href="{{ route('user.edit', $user->id) }}" class=" btn btn-warning btn-lg ">Edit</a>

                            <form action="{{ route('user.destroy', $user->id) }}" method="post">
                                @csrf
                                @method('delete')
                                <button class=" btn btn-danger btn-lg ">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </table>
            <div>
                {{ $users->links() }}
            </div>
        </div>

    </div>
@endsection
@section('script')
    <script>
        $(document).ready(function() {
            $('#searchInput').on('input', function() {
                var searchText = $(this).val().toLowerCase();
                $("table tbody tr").filter(function() {
                    var title = $(this).find('td:eq(1)').text().toLowerCase();
                    var name = $(this).find('td:eq(3)').text().toLowerCase();
                    $(this).toggle(title.indexOf(searchText) > -1 || name.indexOf(searchText) > -1);
                });
            });
        });
    </script>
@endsection